### ISSUE TITLE
AUR release not starting.

### ISSUE THREAD

**Issue by Felting** [altlinux-team/AltLinux#11]
When executed it spits out this error.
Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace Handy not available
[6562] Failed to execute script 'main' due to unhandled exception!

**Comment by Felting** [comment]
I tried git but same error.

**Comment by Felting** [comment]
Fixed by sudo pacman -S libhandy.
